# Accessible in the templates via {{ site.myvariable }}.
first_name: Maxime
last_name: Bellemare
occupation: Computer Science Student

locale: en_CA
type: website
title: Maxime Bellemare
description: >- # this means to ignore newlines until "baseurl:"
  The personal website & blog of Maxime Bellemare.
image: # Add default site image here

favicon: # path to favicon
baseurl: # the subpath of your site, e.g. /blog
url: "http://www.mxblmr.ca" # the base hostname & protocol for your site, e.g. http://example.com

email: hi@mxblmr.ca
twitter_username: mxblmr
github_username:  mxblmr

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
